# Generated by Django 6.0.5 on 2026-06-05 06:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobseekerprofile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('employer', 'Employer'), ('job_seeker', 'Job Seeker'), ('admin', 'Admin')], default='', max_length=20),
        ),
    ]
