# Generated by Django 6.0.5 on 2026-05-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant & Food'), ('events', 'Events & Entertainment'), ('health_care', 'Health & Care'), ('retail', 'Retail & Sales'), ('education', 'Education & Tutoring'), ('other', 'Other')], max_length=50)),
                ('salary_range', models.CharField(blank=True, default='', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('timing', models.CharField(max_length=100)),
                ('slots', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.employerprofile')),
            ],
        ),
    ]
