# Generated by Django 6.0.5 on 2026-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant & Food'), ('events', 'Events & Entertainment'), ('health_care', 'Health & Care'), ('education', 'Education & Tutoring'), ('other', 'Other')], max_length=50),
        ),
    ]
