# Generated by Django 6.0.5 on 2026-05-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant & Food'), ('events', 'Events & Entertainment'), ('health_care', 'Health & Care'), ('education', 'Education & Tutoring'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='timing',
            field=models.CharField(max_length=200),
        ),
    ]
