# Generated by Django 6.0.5 on 2026-05-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_category_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant & Food'), ('events', 'Events & Entertainment'), ('health_care', 'Health & Care'), ('teching', 'Teching & Tutoring'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=100),
        ),
    ]
