# Generated by Django 6.0.5 on 2026-06-05 06:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant & Food'), ('events', 'Events & Entertainment'), ('health_care', 'Health & Care'), ('education', 'Education & Tutoring'), ('delivery', 'Delivery'), ('other', 'Other')], max_length=100),
        ),
    ]
