# Generated by Django 6.0.5 on 2026-05-22 09:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_alter_job_category'),
        ('users', '0003_jobseekerprofile_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('cv_snapshot', models.FileField(blank=True, null=True, upload_to='cvs/applications/')),
                ('has_vehicle', models.BooleanField(blank=True, null=True)),
                ('license_photo', models.ImageField(blank=True, null=True, upload_to='applications/licenses/')),
                ('qualification', models.CharField(blank=True, choices=[('plus_two', 'Plus Two'), ('degree', 'Degree'), ('masters', 'Masters'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=20, null=True)),
                ('experience_details', models.TextField(blank=True, null=True)),
                ('health_certificate', models.FileField(blank=True, null=True, upload_to='applications/health_docs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'png'])])),
                ('employer_note', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.jobseekerprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'seeker')},
            },
        ),
    ]
